tasks:
  - init:  npm install 
  - command: npm i -g cordova && gp sync-done installIT
  - command: gp sync-await installIT && cordova run
  - command: y 
ports:
  - port: 8000
    onOpen: open-browser
